In [ ]:
x = torch.tensor([1., 2, 3],requires_grad = True)

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch

In [ ]:
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y = torch.sum(2 * x)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([2., 2., 2.])

# **Tensor Instantiation and Device**

In [ ]:
x = torch.randn(10000, 10000)

In [ ]:
x.device

device(type='cpu')

In [ ]:
%timeit x ** 3

216 ms ± 7.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
x.to('cuda')

tensor([[ 3.9380e-01, -3.6307e-01, -2.7551e-01,  ..., -8.6402e-04,
         -1.7256e+00, -9.2419e-02],
        [-7.2057e-01,  6.9482e-01,  6.8734e-01,  ...,  1.1710e-01,
          1.5866e+00, -1.2208e+00],
        [-1.0436e+00, -2.6433e+00, -9.8356e-01,  ..., -1.3291e+00,
          9.6770e-01, -7.8871e-02],
        ...,
        [-1.6796e+00, -1.6737e+00, -4.8371e-01,  ...,  4.3471e-01,
         -2.9183e-01,  6.1980e-02],
        [ 8.7491e-01, -7.3202e-01,  1.7640e+00,  ..., -7.4124e-01,
         -1.1523e+00, -8.4375e-01],
        [ 2.1173e-01, -7.4375e-01, -1.2692e+00,  ...,  5.3401e-01,
         -2.5442e-01, -2.0747e-03]], device='cuda:0')

In [ ]:
%timeit x ** 3

212 ms ± 4.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
x.dtype

torch.float32

# Neural Methods

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(10, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 1),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [ ]:
ourNet = NeuralNetwork()


In [ ]:
data = torch.rand(1, 10)

In [ ]:
out = ourNet(data)

In [ ]:
data, out

(tensor([[0.2345, 0.6406, 0.3328, 0.0317, 0.5018, 0.3104, 0.4626, 0.4340, 0.2924,
          0.9660]]),
 tensor([[0.0244]], grad_fn=<AddmmBackward0>))

In [ ]:
loss = nn.L1Loss()

In [ ]:
ourLoss = loss(torch.mean(data), out)

/usr/local/lib/python3.9/dist-packages/torch/nn/modules/loss.py:101: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)


In [ ]:
ourLoss, ourLoss.backward()

(tensor(0.3963, grad_fn=<MeanBackward0>), None)

In [ ]:
torch.tensor([1.]) - 1

tensor([0.])